include info to debug builds

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -7,10 +7,18 @@ matrix:
     - os: linux
 
 before_install:
-  # Clone nonlibc repo as memorywell depends on it.
+  # Clone nonlibc repo as we depend on it but it hasn't been added to nixpkgs
   # TODO: replace this with a nix-channel instead of a download
-  - pushd ~; git clone https://github.com/siriobalmelli/nonlibc.git; popd
+  - |
+    pushd ~
+    git clone https://github.com/siriobalmelli/nonlibc.git
+    popd
 
 script:
-  - nix-build -I ~ --arg dep_type \"static\"
+  - |
+    if ! nix-build -I ~; then
+        echo "build fail! nix-info follows" >&2
+        nix-shell -p nix-info --run "nix-info -m"
+        exit 1
+    fi
 ...
